export const sliderItems = [
  {
    id: 1,
    img: 'https://claue2.arrowtheme.com/pub/media/wysiwyg/slider/Slider_1.jpg',
    title: 'FLASH SALE OF 70%',
    sub: 'Spring - Summer 2021',
    position: 'right',
    desc: 'Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident',
  },
  {
    id: 2,
    img: 'https://claue2.arrowtheme.com/pub/media/wysiwyg/slider/Slider_2_1.jpg',
    title: 'FLASH SALE OF 60%',
    sub: 'Fall - Winter 2021',
    position: 'left',
    desc: 'Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident',
  },
  {
    id: 3,
    img: 'https://claue2.arrowtheme.com/pub/media/wysiwyg/slider/Slider_3.jpg',
    title: 'FLASH SALE OF 50%',
    sub: 'Fashion Trend 2021',
    position: 'left',
    desc: 'Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident',
  },
];

export const categories = [
  {
    id: 1,
    img: 'https://claue2.arrowtheme.com/media/catalog/product/cache/7649c00d5b6f2ce008ff0e304126e2fc/r/e/rectangle_67_1.png',
    type: 'Blazer',
  },
  {
    id: 2,
    img: 'https://claue2.arrowtheme.com/media/catalog/product/cache/7649c00d5b6f2ce008ff0e304126e2fc/r/e/rectangle68.png',
    type: 'Jean Shirt',
  },
  {
    id: 3,
    img: 'https://claue2.arrowtheme.com/media/catalog/product/cache/7649c00d5b6f2ce008ff0e304126e2fc/r/e/rectangle_63.png',
    type: 'Hoodie',
  },
  {
    id: 4,
    img: 'http://74.arrowhitech.net/gpm/claue2.0/pub/media/catalog/product/cache/7649c00d5b6f2ce008ff0e304126e2fc/9/_/9_1_6.jpg',
    type: 'Cuffed Beanie',
  },
];

export const products = [
  {
    id: 1,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-13.jpg',
    isTrending: false,
    name: 'Basic Joggin Shorts',
    price: '$75.00',
    originPrice: '$90.00',
  },
  {
    id: 2,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-16.jpg',
    isTrending: false,
    name: 'Simple Rounded Sunglasses',
    price: '$49.00',
    originPrice: '$75.00',
  },
  {
    id: 3,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-19.jpg',
    isTrending: false,
    name: 'Faded Grey T-Shirt',
    price: '$62.00',
    originPrice: '$121.00',
  },
  {
    id: 4,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-38.jpg',
    isTrending: false,
    name: 'Lined Caro Blazer',
    price: '$37.00',
    originPrice: '$79.00',
  },
  {
    id: 5,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-39.jpg',
    isTrending: false,
    name: 'White Croptop Fabric',
    price: '$115.00',
    originPrice: '$125.00',
  },
  {
    id: 6,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-37.jpg',
    isTrending: false,
    name: 'Simple Backpack Grey Color',
    price: '$60.00',
    originPrice: '$98.00',
  },
  {
    id: 7,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-1.jpg',
    isTrending: true,
    name: 'Simple Black T-Shirt',
    price: '$48.00',
    originPrice: '$68.00',
    img_detail:
      'https://template.hasthemes.com/norda/norda/assets/images/product-details/b-large-1.jpg',
  },
  {
    id: 8,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-2.jpg',
    isTrending: false,
    name: 'Black Simple Sneaker',
    price: '$39.00',
    originPrice: '$59.00',
  },
  {
    id: 9,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-3.jpg',
    isTrending: true,
    name: 'Norda Sport Sneaker',
    price: '$62.00',
    originPrice: '$72.00',
  },
  {
    id: 10,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-7.jpg',
    isTrending: true,
    name: 'Silver High Heel Shoes',
    price: '$54.00',
    originPrice: '$104.00',
  },
  {
    id: 11,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-5.jpg',
    isTrending: true,
    name: 'Contrasting Sunglasses',
    price: '$251.00',
    originPrice: '$301.00',
  },
  {
    id: 12,
    img: 'https://template.hasthemes.com/norda/norda/assets/images/product/product-4.jpg',
    isTrending: true,
    name: 'Norda Simple Backpack',
    price: '$109.00',
    originPrice: null,
  },
];
